version: '3.8'

services:
  database:
    image: mongo
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: API_DB_MOV_CONTAINER
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - dev
    volumes:
      - mongodb_api:/data/db
  backend:
    build:
      context: ./backend
    depends_on:
      - database
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      - demo
      - dev
    ports:
      - '4200:4200'
    environment:
      - MONGO_URL=mongodb://database:27017/api
    volumes:
      - ./backend/src:/usr/src/app/src

networks:
  demo:
  dev:
volumes:
  mongodb_api:
